remote_theme: pages-themes/minimal@v0.2.0
title: Instructional Modes at SUNY Geneseo
description: "Definitions and practices proposed by the Center for Digital Learning"
logo: "/images/cdl-blog-logo-33.png"