remote_theme: pages-themes/minimal@v0.2.0
title: Instructional Modes at SUNY Geneseo
description: "Proposed definitions and practices. This document is a draft."
# logo: "/images/cdl-blog-logo-small.png"