remote_theme: pages-themes/minimal@v0.2.0
title: Instructional Modes at SUNY Geneseo
description: "Definitions and practices developed by the Center for Digital Learning and endorsed by the SUNY Geneseo College Senate 10 May 2022"
logo: "/images/cdl-blog-logo-33.png"