remote_theme: pages-themes/minimal@v0.2.0
title: Instructional Modes at SUNY Geneseo
description: "Proposed definitions and practices. This document is a draft. We welcome your [feedback](https://forms.gle/7WyyjajGYijPfFTb8)."